// flow-typed signature: 3dd3225991f27a1899b773b5c953cfb1
// flow-typed version: <<STUB>>/encoding_v^0.1.12/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'encoding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'encoding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'encoding/lib/encoding' {
  declare module.exports: any;
}

declare module 'encoding/lib/iconv-loader' {
  declare module.exports: any;
}

declare module 'encoding/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'encoding/lib/encoding.js' {
  declare module.exports: $Exports<'encoding/lib/encoding'>;
}
declare module 'encoding/lib/iconv-loader.js' {
  declare module.exports: $Exports<'encoding/lib/iconv-loader'>;
}
declare module 'encoding/test/test.js' {
  declare module.exports: $Exports<'encoding/test/test'>;
}
