// flow-typed signature: 02c7541b8f42a05b5d572b07b4afc07a
// flow-typed version: <<STUB>>/jsbarcode_v~3.5.8/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsbarcode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsbarcode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsbarcode/automation/building' {
  declare module.exports: any;
}

declare module 'jsbarcode/automation/linting' {
  declare module.exports: any;
}

declare module 'jsbarcode/automation/misc' {
  declare module.exports: any;
}

declare module 'jsbarcode/automation/releasing' {
  declare module.exports: any;
}

declare module 'jsbarcode/automation/shared' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/Barcode' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/codabar/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/CODE128/CODE128_AUTO' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/CODE128/CODE128' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/CODE128/CODE128A' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/CODE128/CODE128B' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/CODE128/CODE128C' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/CODE128/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/CODE39/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/EAN_UPC/ean_encoder' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/EAN_UPC/EAN13' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/EAN_UPC/EAN2' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/EAN_UPC/EAN5' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/EAN_UPC/EAN8' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/EAN_UPC/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/EAN_UPC/UPC' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/GenericBarcode/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/index.tmp' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/ITF/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/ITF14/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/MSI/checksums' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/MSI/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/MSI/MSI' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/MSI/MSI10' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/MSI/MSI1010' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/MSI/MSI11' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/MSI/MSI1110' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/barcodes/pharmacode/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/exceptions/ErrorHandler' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/exceptions/exceptions' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/help/fixOptions' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/help/getOptionsFromElement' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/help/getRenderProperties' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/help/linearizeEncodings' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/help/merge' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/help/optionsFromStrings' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/JsBarcode' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/options/defaults' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/renderers/canvas' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/renderers/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/renderers/shared' {
  declare module.exports: any;
}

declare module 'jsbarcode/bin/renderers/svg' {
  declare module.exports: any;
}

declare module 'jsbarcode/dist/barcodes/JsBarcode.codabar.min' {
  declare module.exports: any;
}

declare module 'jsbarcode/dist/barcodes/JsBarcode.code128.min' {
  declare module.exports: any;
}

declare module 'jsbarcode/dist/barcodes/JsBarcode.code39.min' {
  declare module.exports: any;
}

declare module 'jsbarcode/dist/barcodes/JsBarcode.ean-upc.min' {
  declare module.exports: any;
}

declare module 'jsbarcode/dist/barcodes/JsBarcode.itf-14.min' {
  declare module.exports: any;
}

declare module 'jsbarcode/dist/barcodes/JsBarcode.itf.min' {
  declare module.exports: any;
}

declare module 'jsbarcode/dist/barcodes/JsBarcode.msi.min' {
  declare module.exports: any;
}

declare module 'jsbarcode/dist/barcodes/JsBarcode.pharmacode.min' {
  declare module.exports: any;
}

declare module 'jsbarcode/dist/JsBarcode.all' {
  declare module.exports: any;
}

declare module 'jsbarcode/dist/JsBarcode.all.min' {
  declare module.exports: any;
}

declare module 'jsbarcode/gulpfile' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/Barcode' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/codabar/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/CODE128/CODE128_AUTO' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/CODE128/CODE128' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/CODE128/CODE128A' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/CODE128/CODE128B' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/CODE128/CODE128C' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/CODE128/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/CODE39/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/EAN_UPC/ean_encoder' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/EAN_UPC/EAN13' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/EAN_UPC/EAN2' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/EAN_UPC/EAN5' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/EAN_UPC/EAN8' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/EAN_UPC/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/EAN_UPC/UPC' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/GenericBarcode/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/ITF/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/ITF14/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/MSI/checksums' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/MSI/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/MSI/MSI' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/MSI/MSI10' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/MSI/MSI1010' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/MSI/MSI11' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/MSI/MSI1110' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/barcodes/pharmacode/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/exceptions/ErrorHandler' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/exceptions/exceptions' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/help/fixOptions' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/help/getOptionsFromElement' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/help/getRenderProperties' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/help/linearizeEncodings' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/help/merge' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/help/optionsFromStrings' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/JsBarcode' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/options/defaults' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/renderers/canvas' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/renderers/index' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/renderers/shared' {
  declare module.exports: any;
}

declare module 'jsbarcode/src/renderers/svg' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/browser/canvasTest' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/browser/help/jquery-2.2.3' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/browser/jQueryTest' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/browser/svgTest' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/browser/tests' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/node/codabar.test' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/node/CODE128.test' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/node/CODE39.test' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/node/EAN-UPC.test' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/node/help/help' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/node/ITF-14.test' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/node/ITF.test' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/node/JsBarcode.test' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/node/MSI.test' {
  declare module.exports: any;
}

declare module 'jsbarcode/test/node/pharmacode.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsbarcode/automation/building.js' {
  declare module.exports: $Exports<'jsbarcode/automation/building'>;
}
declare module 'jsbarcode/automation/linting.js' {
  declare module.exports: $Exports<'jsbarcode/automation/linting'>;
}
declare module 'jsbarcode/automation/misc.js' {
  declare module.exports: $Exports<'jsbarcode/automation/misc'>;
}
declare module 'jsbarcode/automation/releasing.js' {
  declare module.exports: $Exports<'jsbarcode/automation/releasing'>;
}
declare module 'jsbarcode/automation/shared.js' {
  declare module.exports: $Exports<'jsbarcode/automation/shared'>;
}
declare module 'jsbarcode/bin/barcodes/Barcode.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/Barcode'>;
}
declare module 'jsbarcode/bin/barcodes/codabar/index.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/codabar/index'>;
}
declare module 'jsbarcode/bin/barcodes/CODE128/CODE128_AUTO.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/CODE128/CODE128_AUTO'>;
}
declare module 'jsbarcode/bin/barcodes/CODE128/CODE128.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/CODE128/CODE128'>;
}
declare module 'jsbarcode/bin/barcodes/CODE128/CODE128A.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/CODE128/CODE128A'>;
}
declare module 'jsbarcode/bin/barcodes/CODE128/CODE128B.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/CODE128/CODE128B'>;
}
declare module 'jsbarcode/bin/barcodes/CODE128/CODE128C.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/CODE128/CODE128C'>;
}
declare module 'jsbarcode/bin/barcodes/CODE128/index.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/CODE128/index'>;
}
declare module 'jsbarcode/bin/barcodes/CODE39/index.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/CODE39/index'>;
}
declare module 'jsbarcode/bin/barcodes/EAN_UPC/ean_encoder.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/EAN_UPC/ean_encoder'>;
}
declare module 'jsbarcode/bin/barcodes/EAN_UPC/EAN13.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/EAN_UPC/EAN13'>;
}
declare module 'jsbarcode/bin/barcodes/EAN_UPC/EAN2.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/EAN_UPC/EAN2'>;
}
declare module 'jsbarcode/bin/barcodes/EAN_UPC/EAN5.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/EAN_UPC/EAN5'>;
}
declare module 'jsbarcode/bin/barcodes/EAN_UPC/EAN8.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/EAN_UPC/EAN8'>;
}
declare module 'jsbarcode/bin/barcodes/EAN_UPC/index.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/EAN_UPC/index'>;
}
declare module 'jsbarcode/bin/barcodes/EAN_UPC/UPC.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/EAN_UPC/UPC'>;
}
declare module 'jsbarcode/bin/barcodes/GenericBarcode/index.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/GenericBarcode/index'>;
}
declare module 'jsbarcode/bin/barcodes/index.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/index'>;
}
declare module 'jsbarcode/bin/barcodes/index.tmp.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/index.tmp'>;
}
declare module 'jsbarcode/bin/barcodes/ITF/index.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/ITF/index'>;
}
declare module 'jsbarcode/bin/barcodes/ITF14/index.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/ITF14/index'>;
}
declare module 'jsbarcode/bin/barcodes/MSI/checksums.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/MSI/checksums'>;
}
declare module 'jsbarcode/bin/barcodes/MSI/index.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/MSI/index'>;
}
declare module 'jsbarcode/bin/barcodes/MSI/MSI.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/MSI/MSI'>;
}
declare module 'jsbarcode/bin/barcodes/MSI/MSI10.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/MSI/MSI10'>;
}
declare module 'jsbarcode/bin/barcodes/MSI/MSI1010.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/MSI/MSI1010'>;
}
declare module 'jsbarcode/bin/barcodes/MSI/MSI11.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/MSI/MSI11'>;
}
declare module 'jsbarcode/bin/barcodes/MSI/MSI1110.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/MSI/MSI1110'>;
}
declare module 'jsbarcode/bin/barcodes/pharmacode/index.js' {
  declare module.exports: $Exports<'jsbarcode/bin/barcodes/pharmacode/index'>;
}
declare module 'jsbarcode/bin/exceptions/ErrorHandler.js' {
  declare module.exports: $Exports<'jsbarcode/bin/exceptions/ErrorHandler'>;
}
declare module 'jsbarcode/bin/exceptions/exceptions.js' {
  declare module.exports: $Exports<'jsbarcode/bin/exceptions/exceptions'>;
}
declare module 'jsbarcode/bin/help/fixOptions.js' {
  declare module.exports: $Exports<'jsbarcode/bin/help/fixOptions'>;
}
declare module 'jsbarcode/bin/help/getOptionsFromElement.js' {
  declare module.exports: $Exports<'jsbarcode/bin/help/getOptionsFromElement'>;
}
declare module 'jsbarcode/bin/help/getRenderProperties.js' {
  declare module.exports: $Exports<'jsbarcode/bin/help/getRenderProperties'>;
}
declare module 'jsbarcode/bin/help/linearizeEncodings.js' {
  declare module.exports: $Exports<'jsbarcode/bin/help/linearizeEncodings'>;
}
declare module 'jsbarcode/bin/help/merge.js' {
  declare module.exports: $Exports<'jsbarcode/bin/help/merge'>;
}
declare module 'jsbarcode/bin/help/optionsFromStrings.js' {
  declare module.exports: $Exports<'jsbarcode/bin/help/optionsFromStrings'>;
}
declare module 'jsbarcode/bin/JsBarcode.js' {
  declare module.exports: $Exports<'jsbarcode/bin/JsBarcode'>;
}
declare module 'jsbarcode/bin/options/defaults.js' {
  declare module.exports: $Exports<'jsbarcode/bin/options/defaults'>;
}
declare module 'jsbarcode/bin/renderers/canvas.js' {
  declare module.exports: $Exports<'jsbarcode/bin/renderers/canvas'>;
}
declare module 'jsbarcode/bin/renderers/index.js' {
  declare module.exports: $Exports<'jsbarcode/bin/renderers/index'>;
}
declare module 'jsbarcode/bin/renderers/shared.js' {
  declare module.exports: $Exports<'jsbarcode/bin/renderers/shared'>;
}
declare module 'jsbarcode/bin/renderers/svg.js' {
  declare module.exports: $Exports<'jsbarcode/bin/renderers/svg'>;
}
declare module 'jsbarcode/dist/barcodes/JsBarcode.codabar.min.js' {
  declare module.exports: $Exports<'jsbarcode/dist/barcodes/JsBarcode.codabar.min'>;
}
declare module 'jsbarcode/dist/barcodes/JsBarcode.code128.min.js' {
  declare module.exports: $Exports<'jsbarcode/dist/barcodes/JsBarcode.code128.min'>;
}
declare module 'jsbarcode/dist/barcodes/JsBarcode.code39.min.js' {
  declare module.exports: $Exports<'jsbarcode/dist/barcodes/JsBarcode.code39.min'>;
}
declare module 'jsbarcode/dist/barcodes/JsBarcode.ean-upc.min.js' {
  declare module.exports: $Exports<'jsbarcode/dist/barcodes/JsBarcode.ean-upc.min'>;
}
declare module 'jsbarcode/dist/barcodes/JsBarcode.itf-14.min.js' {
  declare module.exports: $Exports<'jsbarcode/dist/barcodes/JsBarcode.itf-14.min'>;
}
declare module 'jsbarcode/dist/barcodes/JsBarcode.itf.min.js' {
  declare module.exports: $Exports<'jsbarcode/dist/barcodes/JsBarcode.itf.min'>;
}
declare module 'jsbarcode/dist/barcodes/JsBarcode.msi.min.js' {
  declare module.exports: $Exports<'jsbarcode/dist/barcodes/JsBarcode.msi.min'>;
}
declare module 'jsbarcode/dist/barcodes/JsBarcode.pharmacode.min.js' {
  declare module.exports: $Exports<'jsbarcode/dist/barcodes/JsBarcode.pharmacode.min'>;
}
declare module 'jsbarcode/dist/JsBarcode.all.js' {
  declare module.exports: $Exports<'jsbarcode/dist/JsBarcode.all'>;
}
declare module 'jsbarcode/dist/JsBarcode.all.min.js' {
  declare module.exports: $Exports<'jsbarcode/dist/JsBarcode.all.min'>;
}
declare module 'jsbarcode/gulpfile.js' {
  declare module.exports: $Exports<'jsbarcode/gulpfile'>;
}
declare module 'jsbarcode/src/barcodes/Barcode.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/Barcode'>;
}
declare module 'jsbarcode/src/barcodes/codabar/index.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/codabar/index'>;
}
declare module 'jsbarcode/src/barcodes/CODE128/CODE128_AUTO.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/CODE128/CODE128_AUTO'>;
}
declare module 'jsbarcode/src/barcodes/CODE128/CODE128.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/CODE128/CODE128'>;
}
declare module 'jsbarcode/src/barcodes/CODE128/CODE128A.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/CODE128/CODE128A'>;
}
declare module 'jsbarcode/src/barcodes/CODE128/CODE128B.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/CODE128/CODE128B'>;
}
declare module 'jsbarcode/src/barcodes/CODE128/CODE128C.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/CODE128/CODE128C'>;
}
declare module 'jsbarcode/src/barcodes/CODE128/index.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/CODE128/index'>;
}
declare module 'jsbarcode/src/barcodes/CODE39/index.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/CODE39/index'>;
}
declare module 'jsbarcode/src/barcodes/EAN_UPC/ean_encoder.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/EAN_UPC/ean_encoder'>;
}
declare module 'jsbarcode/src/barcodes/EAN_UPC/EAN13.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/EAN_UPC/EAN13'>;
}
declare module 'jsbarcode/src/barcodes/EAN_UPC/EAN2.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/EAN_UPC/EAN2'>;
}
declare module 'jsbarcode/src/barcodes/EAN_UPC/EAN5.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/EAN_UPC/EAN5'>;
}
declare module 'jsbarcode/src/barcodes/EAN_UPC/EAN8.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/EAN_UPC/EAN8'>;
}
declare module 'jsbarcode/src/barcodes/EAN_UPC/index.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/EAN_UPC/index'>;
}
declare module 'jsbarcode/src/barcodes/EAN_UPC/UPC.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/EAN_UPC/UPC'>;
}
declare module 'jsbarcode/src/barcodes/GenericBarcode/index.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/GenericBarcode/index'>;
}
declare module 'jsbarcode/src/barcodes/index.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/index'>;
}
declare module 'jsbarcode/src/barcodes/ITF/index.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/ITF/index'>;
}
declare module 'jsbarcode/src/barcodes/ITF14/index.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/ITF14/index'>;
}
declare module 'jsbarcode/src/barcodes/MSI/checksums.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/MSI/checksums'>;
}
declare module 'jsbarcode/src/barcodes/MSI/index.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/MSI/index'>;
}
declare module 'jsbarcode/src/barcodes/MSI/MSI.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/MSI/MSI'>;
}
declare module 'jsbarcode/src/barcodes/MSI/MSI10.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/MSI/MSI10'>;
}
declare module 'jsbarcode/src/barcodes/MSI/MSI1010.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/MSI/MSI1010'>;
}
declare module 'jsbarcode/src/barcodes/MSI/MSI11.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/MSI/MSI11'>;
}
declare module 'jsbarcode/src/barcodes/MSI/MSI1110.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/MSI/MSI1110'>;
}
declare module 'jsbarcode/src/barcodes/pharmacode/index.js' {
  declare module.exports: $Exports<'jsbarcode/src/barcodes/pharmacode/index'>;
}
declare module 'jsbarcode/src/exceptions/ErrorHandler.js' {
  declare module.exports: $Exports<'jsbarcode/src/exceptions/ErrorHandler'>;
}
declare module 'jsbarcode/src/exceptions/exceptions.js' {
  declare module.exports: $Exports<'jsbarcode/src/exceptions/exceptions'>;
}
declare module 'jsbarcode/src/help/fixOptions.js' {
  declare module.exports: $Exports<'jsbarcode/src/help/fixOptions'>;
}
declare module 'jsbarcode/src/help/getOptionsFromElement.js' {
  declare module.exports: $Exports<'jsbarcode/src/help/getOptionsFromElement'>;
}
declare module 'jsbarcode/src/help/getRenderProperties.js' {
  declare module.exports: $Exports<'jsbarcode/src/help/getRenderProperties'>;
}
declare module 'jsbarcode/src/help/linearizeEncodings.js' {
  declare module.exports: $Exports<'jsbarcode/src/help/linearizeEncodings'>;
}
declare module 'jsbarcode/src/help/merge.js' {
  declare module.exports: $Exports<'jsbarcode/src/help/merge'>;
}
declare module 'jsbarcode/src/help/optionsFromStrings.js' {
  declare module.exports: $Exports<'jsbarcode/src/help/optionsFromStrings'>;
}
declare module 'jsbarcode/src/JsBarcode.js' {
  declare module.exports: $Exports<'jsbarcode/src/JsBarcode'>;
}
declare module 'jsbarcode/src/options/defaults.js' {
  declare module.exports: $Exports<'jsbarcode/src/options/defaults'>;
}
declare module 'jsbarcode/src/renderers/canvas.js' {
  declare module.exports: $Exports<'jsbarcode/src/renderers/canvas'>;
}
declare module 'jsbarcode/src/renderers/index.js' {
  declare module.exports: $Exports<'jsbarcode/src/renderers/index'>;
}
declare module 'jsbarcode/src/renderers/shared.js' {
  declare module.exports: $Exports<'jsbarcode/src/renderers/shared'>;
}
declare module 'jsbarcode/src/renderers/svg.js' {
  declare module.exports: $Exports<'jsbarcode/src/renderers/svg'>;
}
declare module 'jsbarcode/test/browser/canvasTest.js' {
  declare module.exports: $Exports<'jsbarcode/test/browser/canvasTest'>;
}
declare module 'jsbarcode/test/browser/help/jquery-2.2.3.js' {
  declare module.exports: $Exports<'jsbarcode/test/browser/help/jquery-2.2.3'>;
}
declare module 'jsbarcode/test/browser/jQueryTest.js' {
  declare module.exports: $Exports<'jsbarcode/test/browser/jQueryTest'>;
}
declare module 'jsbarcode/test/browser/svgTest.js' {
  declare module.exports: $Exports<'jsbarcode/test/browser/svgTest'>;
}
declare module 'jsbarcode/test/browser/tests.js' {
  declare module.exports: $Exports<'jsbarcode/test/browser/tests'>;
}
declare module 'jsbarcode/test/node/codabar.test.js' {
  declare module.exports: $Exports<'jsbarcode/test/node/codabar.test'>;
}
declare module 'jsbarcode/test/node/CODE128.test.js' {
  declare module.exports: $Exports<'jsbarcode/test/node/CODE128.test'>;
}
declare module 'jsbarcode/test/node/CODE39.test.js' {
  declare module.exports: $Exports<'jsbarcode/test/node/CODE39.test'>;
}
declare module 'jsbarcode/test/node/EAN-UPC.test.js' {
  declare module.exports: $Exports<'jsbarcode/test/node/EAN-UPC.test'>;
}
declare module 'jsbarcode/test/node/help/help.js' {
  declare module.exports: $Exports<'jsbarcode/test/node/help/help'>;
}
declare module 'jsbarcode/test/node/ITF-14.test.js' {
  declare module.exports: $Exports<'jsbarcode/test/node/ITF-14.test'>;
}
declare module 'jsbarcode/test/node/ITF.test.js' {
  declare module.exports: $Exports<'jsbarcode/test/node/ITF.test'>;
}
declare module 'jsbarcode/test/node/JsBarcode.test.js' {
  declare module.exports: $Exports<'jsbarcode/test/node/JsBarcode.test'>;
}
declare module 'jsbarcode/test/node/MSI.test.js' {
  declare module.exports: $Exports<'jsbarcode/test/node/MSI.test'>;
}
declare module 'jsbarcode/test/node/pharmacode.test.js' {
  declare module.exports: $Exports<'jsbarcode/test/node/pharmacode.test'>;
}
