// flow-typed signature: 8a4c4ea1c343b3d0bdde1c76f830c302
// flow-typed version: <<STUB>>/normalize.css_vv4.2.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
