// flow-typed signature: 4ef4360b22a294537b7d72e37afb168e
// flow-typed version: <<STUB>>/qrcode.react_v~0.6.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qrcode.react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qrcode.react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qrcode.react/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qrcode.react/lib/index.js' {
  declare module.exports: $Exports<'qrcode.react/lib/index'>;
}
